name: bisect
description: A library that implements a simple bisection algorithm for insertion in sorted lists.
version: 1.0.0
license: MIT
repository: https://github.com/Israel77/Bisect

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
