name: bisect
description: A library that implements a simple bisection algorithm for insertion in sorted lists.
version: 2.0.0
license: MIT
repository: https://github.com/Israel77/Bisect

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.8
